### ISSUE TITLE
Improvement:  get of redis instances to monitor from CLUSTER NODES command

### ISSUE THREAD

**Issue by allanwax** [junegunn/redis-stat#20]
Currently you need to list all the instances you want to watch on the command line.  This allows you to only monitor what you want.  It is also tedious if the number of machines is large.

It would be nice if there was an option applicable to redis cluster (currently in RC1) whereby you only need to specify one machine in the cluster.  From that machine issuing a CLUSTER NODES command will list all the members of the cluster.  Then use that list to specify the machines to monitor.

**Comment by amit-handa** [comment]
sorry to bother. But is there any plan of supporting cluster config changes in redis-stat ?

**Comment by junegunn** [comment]
@amit-handa Sorry, no plan. I'm not actively developing redis-stat any more.
