### ISSUE TITLE
Error:  Did not recognize your adapter specification (cannot load such file -- json/ext/parser)

### ISSUE THREAD

**Issue by rustychapin** [junegunn/redis-stat#32]
Hi there!  Love this tool and am working on getting it connected to my ElasticSearch.  When I start redis-stat with --verbose I get the following error.  Can you help point me in the right direction here?

Here is my command line:
redis-stat 192.168.255.255:6379 --server=801 --es=http://192.168.254.254:9200/redis-stat --verbose

**Comment by junegunn** [comment]
Hi, I can't reproduce the problem with redis-stat 0.4.10 on Ruby 2.1.2 and 2.2.0. Are you running the latest version of redis-stat?
