### ISSUE TITLE
Can not reconnect after flushing big database

### ISSUE THREAD

**Issue by 3Dragan** [junegunn/redis-stat#33]
After running FLUSHALL or FLUSHDB for big database, it seems that redis-stat server loose connection and can not reconnect, show authentication problem on UI.

**Comment by junegunn** [comment]
Thanks for the report. Looks like Redis changed its message for requiring authentication some time ago. I'll build a new version and let you know.

**Comment by 3Dragan** [comment]
Will wait for it. 
Thank you for fast reply.

**Comment by junegunn** [comment]
0.4.11 is up on Rubygems, and I uploaded the new executable jar on releases page. Thanks.
