### ISSUE TITLE
"redis-stat --server" this command is suited for localhost, it do not work for remote server?Right?

### ISSUE THREAD

**Issue by no13bus** [junegunn/redis-stat#34]
when I run this command `redis-stat --server`, I can not monitor the remote server, just some command like `redis-stat --server=106.11.188.12:6379`. Am I right?

Besides, I type this command: `redis-stat 182.92.155.88:6379 localhost:6379 1`. And this is the result below:

![img](http://ww3.sinaimg.cn/large/9a24d3aftw1eprvoxm25dj20og0dydla.jpg)

there are two redis service in two machines.
So I want to ask the result with colorful message shows one redis info or two redis-info?The mem info seem like one machine's info. Did two redis info showed in sequence accoding to the result.

**Comment by junegunn** [comment]
> when I run this command redis-stat --server, I can not monitor the remote server, just some command like redis-stat --server=106.11.188.12:6379. Am I right?

No. Please reread the README page of the project.

> So I want to ask the result with colorful message shows one redis info or two redis-info?

The console log shows the aggregate metrics of the redis instances. But you can see the stats of each instance on the browser (`--server`) using the dropdown menu.

**Comment by priyaguntur** [comment]
Redis-stat is working fine for me , but its not running in web-browser when i attempt to redis-stat --server it is giving the stats in command prompt i didnt understand the problem, can u plz help me in this..
