### ISSUE TITLE
how to resolve this problem,please?

### ISSUE THREAD

**Issue by azhong** [junegunn/redis-stat#36]
followed below scripts to install ruby & rubygems：yum install ruby;
but when starting redis-stat，error info：
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- redis-stat (LoadError)
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from ./redis-stat:4:in `<main>'

how can I resolve this problem，please?

**Comment by junegunn** [comment]
I think you forgot to mention how you installed redis-stat. `gem install redis-stat`?

Please provide me with the following information:
- Your OS distro and version
- Ruby version: `ruby -v`
- Gem version: `gem -v`
- `gem list | grep redis-stat`

**Comment by azhong** [comment]
Thank you！I did really forgot install redis-stat。
now when I gem list | grep reids-stat，nothing happend，it's blank. why？

**Comment by azhong** [comment]
add：
gem -v ： 2.0.14
ruby -v：2.0.0p598
OS:   centos 7

**Comment by junegunn** [comment]
> now when I gem list | grep reids-stat，nothing happend，it's blank. why？

Is "reids" a typo?

Please post the exact output of the following commands:

```sh
gem install redis-stat
gem list | grep redis-stat
which redis-stat
```

**Comment by azhong** [comment]
![1](https://cloud.githubusercontent.com/assets/1209589/7173635/60293152-e42d-11e4-9873-026c22904a2f.jpg)

**Comment by junegunn** [comment]
What about `gem install redis-stat`, what does it say?

**Comment by azhong** [comment]
nothing happened,like gem list  | grep redis-stat.

**Comment by junegunn** [comment]
You mean, no message at all when you try `gem install`? Then it looks like redis-stat is not properly installed. Have you tried installing it with `sudo gem install redis-stat`?

**Comment by azhong** [comment]
yes,no message at all.I think gem can not find package of redis-stat.

**Comment by junegunn** [comment]
Well, then I can't help you. You'll have to figure out yourself why Rubygems are not working as expected on your system. If you really can't solve the problem, you might want to consider using the JAR distribution.

https://github.com/junegunn/redis-stat/releases
