### ISSUE TITLE
Graphs for hit ratio percentage

### ISSUE THREAD

**Issue by blindpet** [junegunn/redis-stat#40]
Just a request for overall hit ratio percentage graphs. Thanks for your work.

Similar to this opcache monitor https://raw.github.com/rlerdorf/opcache-status/master/opcache.php

http://i.imgur.com/BZswvb4.png
http://i.imgur.com/ydykW1h.png

**Comment by junegunn** [comment]
I don't use redis much these days, and due to my lack of interest in it, I'm not actively maintaining this project. You can fork the repository and bend it to your needs and I'm open to pull requests.
