### ISSUE TITLE
Error while running redis-stat

### ISSUE THREAD

**Issue by heera-jaiswal** [junegunn/redis-stat#63]
After successfully installed
On running
`redis-stat localhost:6379/<password>`
Getting following error
`-bash: !dg3: event not found`

OS: aws amazon linux(centos)

**Comment by junegunn** [comment]
Does your password contain `!`? Try wrapping the argument with single quotes so that it's not expanded by the shell. `redis-stat 'localhost:6379/<password>'`

**Comment by heera-jaiswal** [comment]
Thanks. It worked ! 👍
