### ISSUE TITLE
How to get the web page 

### ISSUE THREAD

**Issue by StartRightNow926** [junegunn/redis-stat#73]
When I run the redis-stat,the terminal show that
 == Sinatra/1.3.6 has taken the stage on 63790 for production with backup from Thin
>> Thin web server (v1.5.1 codename Straight Razor)
>> Maximum connections set to 1024
>> Listening on 0.0.0.0:63790
Why the web page in 0.0.0.0 and how can I access the page?

**Comment by junegunn** [comment]
Try `http://localhost:63790`

**Comment by StartRightNow926** [comment]
it doesn't work.why the web in 0.0.0.0,how to set the ip address of the web ?

**Comment by junegunn** [comment]
Or `127.0.0.1:63790`? "Listening" on `0.0.0.0` doesn't mean that `0.0.0.0` is the address of the web server.

**Comment by StartRightNow926** [comment]
I know the address , 0.0.0.0 is a reserved address,you can use the ip address of your host to access the web page,but I try the 127.0.0.1 and localhost,it doesn't work.I want to know how to can set the page in a specific address,or why is it listening 0.0.0.0?when I set it in my computer ,it work.But when I set it on the cluster, it doesn't work?
